import type { InvoiceView } from '@anura/shared';

/**
 * Opens a print-ready invoice in a new window and triggers the browser print
 * dialog, from which the user can "Save as PDF". No PDF dependency required.
 */
export function printInvoice(invoice: InvoiceView, fromName: string): boolean {
  const win = window.open('', '_blank', 'width=840,height=1000');
  if (!win) return false; // popup blocked

  const currency = invoice.currency || 'INR';
  const money = (n: number) =>
    new Intl.NumberFormat('en-IN', {
      style: 'currency',
      currency,
      maximumFractionDigits: n % 1 === 0 ? 0 : 2,
    }).format(n);
  const date = (iso: string | null) => {
    if (!iso) return '—';
    const d = new Date(iso);
    return Number.isNaN(d.getTime())
      ? '—'
      : d.toLocaleDateString('en-IN', { day: '2-digit', month: 'short', year: 'numeric' });
  };

  const rows = invoice.items
    .map(
      (it) => `<tr>
        <td>${esc(it.description)}</td>
        <td class="num">${it.quantity}</td>
        <td class="num">${money(it.unitPrice)}</td>
        <td class="num">${money(it.amount)}</td>
      </tr>`,
    )
    .join('');

  const html = `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8" />
<title>Invoice ${esc(invoice.number)}</title>
<style>
  * { box-sizing: border-box; }
  body { font-family: 'Plus Jakarta Sans', system-ui, -apple-system, 'Segoe UI', Roboto, sans-serif; color: #0A0E1A; margin: 0; padding: 40px; }
  .head { display: flex; justify-content: space-between; align-items: flex-start; border-bottom: 2px solid #0A0E1A; padding-bottom: 20px; }
  .brand { font-size: 26px; font-weight: 700; letter-spacing: -0.02em; }
  .brand small { display:block; font-size: 13px; font-weight: 500; color: #5B5BE8; letter-spacing: 0; }
  .inv-meta { text-align: right; }
  .inv-meta h1 { margin: 0 0 4px; font-size: 20px; }
  .muted { color: #6b7280; }
  .parties { display: flex; justify-content: space-between; gap: 24px; margin: 28px 0; font-size: 14px; }
  .parties h3 { margin: 0 0 6px; font-size: 11px; text-transform: uppercase; letter-spacing: 0.06em; color: #6b7280; }
  table { width: 100%; border-collapse: collapse; margin-top: 8px; font-size: 14px; }
  th { text-align: left; text-transform: uppercase; font-size: 11px; letter-spacing: 0.05em; color: #6b7280; border-bottom: 1px solid #e5e7eb; padding: 8px 10px; }
  td { padding: 10px; border-bottom: 1px solid #f0f0ee; }
  th.num, td.num { text-align: right; font-variant-numeric: tabular-nums; }
  .totals { margin-left: auto; width: 280px; margin-top: 18px; font-size: 14px; }
  .totals .row { display: flex; justify-content: space-between; padding: 4px 0; color: #6b7280; }
  .totals .row span:last-child { color: #0A0E1A; font-variant-numeric: tabular-nums; }
  .totals .grand { border-top: 1px solid #0A0E1A; margin-top: 8px; padding-top: 10px; font-size: 17px; font-weight: 700; }
  .totals .grand span { color: #0A0E1A !important; }
  .foot { margin-top: 48px; font-size: 12px; color: #9ca3af; border-top: 1px solid #f0f0ee; padding-top: 16px; }
  @media print { body { padding: 24px; } @page { margin: 16mm; } }
</style>
</head>
<body>
  <div class="head">
    <div class="brand">${esc(fromName)}<small>via Anura</small></div>
    <div class="inv-meta">
      <h1>INVOICE</h1>
      <div class="muted">${esc(invoice.number)}</div>
      <div class="muted">Status: ${esc(cap(invoice.status))}</div>
    </div>
  </div>

  <div class="parties">
    <div>
      <h3>Billed to</h3>
      <div>${esc(invoice.clientName ?? '—')}</div>
    </div>
    <div style="text-align:right">
      <h3>Details</h3>
      <div>Issued: ${date(invoice.issuedAt)}</div>
      <div>Due: ${date(invoice.dueAt)}</div>
    </div>
  </div>

  <table>
    <thead>
      <tr><th>Description</th><th class="num">Qty</th><th class="num">Unit price</th><th class="num">Amount</th></tr>
    </thead>
    <tbody>${rows}</tbody>
  </table>

  <div class="totals">
    <div class="row"><span>Subtotal</span><span>${money(invoice.subtotal)}</span></div>
    <div class="row"><span>GST (${invoice.gstPercent}%)</span><span>${money(invoice.gstAmount)}</span></div>
    <div class="row grand"><span>Total</span><span>${money(invoice.total)}</span></div>
  </div>

  <div class="foot">Generated by Anura · This is a computer-generated invoice.</div>

  <script>window.onload = function () { window.focus(); window.print(); };</script>
</body>
</html>`;

  win.document.open();
  win.document.write(html);
  win.document.close();
  return true;
}

function esc(s: string): string {
  return s.replace(/[&<>"']/g, (c) =>
    ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[c] as string,
  );
}

function cap(s: string): string {
  return s.charAt(0) + s.slice(1).toLowerCase();
}
